### ISSUE TITLE
lmtsh complains about lack of Lua support

### ISSUE THREAD

**Issue by george-b** [LLNL/lmt#32] opened 2018-03-14 14:59 UTC
I have the following installed.

```
$ rpm -qa | grep lua
lua-5.1.4-14.el7.x86_64
lua-devel-5.1.4-14.el7.x86_64
```

In the `config.log` of the LMT build I have the following, abbreviated to what I believe to be the relevant pieces of information but I can provide the full log if required.

```

...

configure:13276: checking lua.h usability
configure:13276: gcc -c -g -O2  conftest.c >&5
configure:13276: $? = 0
configure:13276: result: yes
configure:13276: checking lua.h presence
configure:13276: gcc -E  conftest.c
configure:13276: $? = 0
configure:13276: result: yes
configure:13276: checking for lua.h
configure:13276: result: yes

...

configure:13803: checking for luaL_newstate in default libs
configure:13827: gcc -o conftest -g -O2   conftest.c -lm -ldl  >&5
/tmp/ccuaRyzQ.o: In function `main':
/home/admin/lmt-3.2.0/conftest.c:87: undefined reference to `luaL_newstate'
collect2: error: ld returned 1 exit status
configure:13827: $? = 1

...

configure:13840: checking for luaL_newstate in -llua
configure:13865: gcc -o conftest -g -O2   conftest.c -llua  -lm -ldl  >&5
configure:13865: $? = 0
configure:13874: result: yes

...

ac_cv_header_lua_h=yes

...

ac_cv_lib_lua_luaL_newstate=yes

...

x_ac_cv_lib_none_luaL_newstate=no

...

```

I have set up the database per the wiki and am able to list it.

```
$ /usr/sbin/lmtinit -l -u lwatchadmin -P
Password: 
snx11258
```

However I am unable to use `lmtsh`

```
$ /sbin/lmtsh -v -d
/etc/lmt/lmt.conf: LMT was built without LUA support
[LMT:init] Missing configuration file or configuration info: /etc/lmt/lmt.conf
```

The file `/etc/lmt/lmt.conf` does exist and contains the correct information.

**Comment by george-b** [comment] 2018-03-14 15:01
As an aside the database itself it not being populated with data.

```
MariaDB [filesystem_snx11258]> SELECT * FROM FILESYSTEM_INFO;
+---------------+-----------------+-----------------------+----------------+
| FILESYSTEM_ID | FILESYSTEM_NAME | FILESYSTEM_MOUNT_NAME | SCHEMA_VERSION |
+---------------+-----------------+-----------------------+----------------+
|             1 | snx11258        |                       |            1.1 |
+---------------+-----------------+-----------------------+----------------+
1 row in set (0.01 sec)

MariaDB [filesystem_snx11258]> SELECT * FROM MDS_DATA;
Empty set (0.02 sec)

MariaDB [filesystem_snx11258]> SELECT * FROM MDS_INFO;
Empty set (0.01 sec)
```

**Comment by ofaaland** [comment] 2019-11-25 19:10
I don't see the issue yet.  Some notes so far below.

OP didn't specify an LMT version but at the time the issue was created, the most recent release was 3.2.3.

I haven't found a reason it would be, yet, but I wonder if this is a side-affect of https://github.com/LLNL/lmt/issues/44.

Messages:
```
/etc/lmt/lmt.conf: LMT was built without LUA support
```
This appears to be emitted only by liblmt/lmtconf.c:247 lmt_conf_init(), and only if HAVE_LUA_H is not defined.

```
[LMT:init] Missing configuration file or configuration info: /etc/lmt/lmt.conf
```
$cf is "/etc/lmt/lmt.conf" based on the error message.
This implies ${prefix} is empty ("").
This message comes from scripts/LMT.pm.in:63 when _parseConf($cf) returns an empty hash.
_parseConf() is defined at LMT.pm.in:835.
_parseConf() runs "lmtinit -x -c $cf" and parses its output to populate the hash.  The command must have had no output at all, or failed to run entirely.

```
And the first thing that lmtinit does after parsing options is call lmt_conf_init() which would be expected to fail with the error message above.  So the two error messages are due to the same root cause.

**Comment by george-b** [comment] 2019-11-25 19:50
This was a while ago but I got LMT running though I can't recall what steps I took. I have no longer work on this system so I can't check unfortunately, feel free to close this issue.

**Comment by ofaaland** [comment] 2019-11-25 20:46
OK.  I don't see how to reproduce your symptoms, so closing.  Thanks.

**Closed by ofaaland** 2019-11-25 20:46 UTC
